name: Acceptance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run acceptance tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  acceptance:
    runs-on: ubuntu-latest

    services:
      # Use a headless Chrome for Selenium tests
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2gb
        ports:
          - 4444:4444

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install Chrome for Selenium
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install Chrome WebDriver
      run: |
        wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$(google-chrome --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')/chromedriver_linux64.zip
        sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run acceptance tests
      run: |
        pytest tests/acceptance/ -v --tb=short -x
      env:
        HEADLESS: true

    - name: Upload screenshots on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: selenium-screenshots
        path: screenshots/